// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATJRPxA9HMuoCK3NSVbWlSUZ9hbXAHsvE',
    appId: '1:710399343176:web:026be8dd8bb62b25bef67d',
    messagingSenderId: '710399343176',
    projectId: 'nextdink-11',
    authDomain: 'nextdink-11.firebaseapp.com',
    storageBucket: 'nextdink-11.firebasestorage.app',
    measurementId: 'G-4EVYE0Y3GS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg6tV216lYExeG2vU1bXcvf9691oTIIXE',
    appId: '1:710399343176:android:1040273a2736ab2bbef67d',
    messagingSenderId: '710399343176',
    projectId: 'nextdink-11',
    storageBucket: 'nextdink-11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbMjlpm2rT38gkkES6pmu6TwLkQqnWrkw',
    appId: '1:710399343176:ios:fbcad543b1c688b8bef67d',
    messagingSenderId: '710399343176',
    projectId: 'nextdink-11',
    storageBucket: 'nextdink-11.firebasestorage.app',
    iosClientId: '710399343176-fdoaev51g057t4p8ko7hk6jpsh2ag9vb.apps.googleusercontent.com',
    iosBundleId: 'com.vhpatel73.nextdink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbMjlpm2rT38gkkES6pmu6TwLkQqnWrkw',
    appId: '1:710399343176:ios:fbcad543b1c688b8bef67d',
    messagingSenderId: '710399343176',
    projectId: 'nextdink-11',
    storageBucket: 'nextdink-11.firebasestorage.app',
    iosClientId: '710399343176-fdoaev51g057t4p8ko7hk6jpsh2ag9vb.apps.googleusercontent.com',
    iosBundleId: 'com.vhpatel73.nextdink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATJRPxA9HMuoCK3NSVbWlSUZ9hbXAHsvE',
    appId: '1:710399343176:web:e54ff587a8d7f5f3bef67d',
    messagingSenderId: '710399343176',
    projectId: 'nextdink-11',
    authDomain: 'nextdink-11.firebaseapp.com',
    storageBucket: 'nextdink-11.firebasestorage.app',
    measurementId: 'G-7QZR2716XQ',
  );
}
